# Generated by Django 5.2.4 on 2025-07-28 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='stock',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
